### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by AlexStormwood** [AlexHolderDeveloper/alexholderdeveloper.github.io#4]
- [ ] Add explanations or stories or _something_ to the skills page for each category
- [ ] Add more to the qualifications section of the About Me page 
- [ ] Add photos to the Events & Appearances page
- [ ] Fix the horizontal overflow causing scrolling in the timeline entries of the Employment History page
- [ ] Make the navbar positioning consistent across pages
- [ ] Overhaul the Project page so that projects that are repositories actually pull data from the GitHub REST API
